In [1]:
from data import get_data
from config import data_path, models
from preprocessing import preprocess_train_data
from models import build_models_cv, build_threshold_metrics
from cost import cost_reduction_preprocessor, estimate_cost_reduction

In [2]:
df = get_data(data_path)

d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\data.py:18: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, sep = ',')

In [3]:
df_numeric, df_results = preprocess_train_data(df)

In [15]:
df_results

        readmit_30d  readmit_90d
0                 0            0
1                 0            0
2                 0            0
4                 0            0
6                 0            0
...             ...          ...
109493            0            0
109494            0            1
109495            0            0
109496            0            0
109497            0            0

[67431 rows x 2 columns]

In [4]:
results = build_models_cv(models, df_numeric, df_results)

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[LightGBM] [Info] Number of positive: 1336, number of negative: 52608
[LightGBM] [Info] Total Bins 1403
[LightGBM] [Info] Number of data points in the train set: 53944, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.024766 -> initscore=-3.673188
[LightGBM] [Info] Start training from score -3.673188

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 2573, number of negative: 51371
[LightGBM] [Info] Total Bins 1403
[LightGBM] [Info] Number of data points in the train set: 53944, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.047698 -> initscore=-2.994001
[LightGBM] [Info] Start training from score -2.994001

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[LightGBM] [Info] Number of positive: 1314, number of negative: 52631
[LightGBM] [Info] Total Bins 1404
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.024358 -> initscore=-3.690229
[LightGBM] [Info] Start training from score -3.690229

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 2525, number of negative: 51420
[LightGBM] [Info] Total Bins 1404
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.046807 -> initscore=-3.013786
[LightGBM] [Info] Start training from score -3.013786

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[LightGBM] [Info] Number of positive: 1335, number of negative: 52610
[LightGBM] [Info] Total Bins 1406
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.024747 -> initscore=-3.673975
[LightGBM] [Info] Start training from score -3.673975

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 2568, number of negative: 51377
[LightGBM] [Info] Total Bins 1406
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.047604 -> initscore=-2.996063
[LightGBM] [Info] Start training from score -2.996063

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[LightGBM] [Info] Number of positive: 1315, number of negative: 52630
[LightGBM] [Info] Total Bins 1402
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.024377 -> initscore=-3.689450
[LightGBM] [Info] Start training from score -3.689450

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 2537, number of negative: 51408
[LightGBM] [Info] Total Bins 1402
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.047029 -> initscore=-3.008812
[LightGBM] [Info] Start training from score -3.008812

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[LightGBM] [Info] Number of positive: 1324, number of negative: 52621
[LightGBM] [Info] Total Bins 1408
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.024544 -> initscore=-3.682458
[LightGBM] [Info] Start training from score -3.682458

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Number of positive: 2553, number of negative: 51392
[LightGBM] [Info] Total Bins 1408
[LightGBM] [Info] Number of data points in the train set: 53945, number of used features: 21
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.047326 -> initscore=-3.002213
[LightGBM] [Info] Start training from score -3.002213

d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:221: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  values = pd.concat([values, table])

In [5]:
import pandas as pd
pd.crosstab(results['pred_values']['readmit_30d'], results['pred_values']['readmit_90d'])

readmit_90d      0     1
readmit_30d
0            65775     0
1                0  1656

In [6]:
results['pred_values']

,readmit_30d,readmit_90d,logreg_d30,logreg_d90,rf_d30,rf_d90,lightgbm_d30,lightgbm_d90
0,0,0,0.248579,0.231033,0.077332,0.090923,0.001635,0.005170
1,0,0,0.177173,0.213715,0.032193,0.152009,0.000651,0.016681
2,0,0,0.050790,0.099610,0.031556,0.068344,0.002012,0.005992
4,0,0,0.058711,0.090518,0.006613,0.013784,0.000107,0.001526
6,0,0,0.252291,0.226137,0.060472,0.030303,0.013397,0.006461
...,...,...,...,...,...,...,...,...
109493,0,0,0.469242,0.471163,0.772860,0.850851,0.090160,0.190588
109494,0,0,0.487509,0.483475,0.350828,0.579789,0.046016,0.115891
109495,0,0,0.299854,0.338542,0.000000,0.002759,0.001325,0.003490
109496,0,0,0.663006,0.666239,0.007616,0.076397,0.006345,0.023273
109497,0,0,0.739537,0.702341,0.306096,0.521167,0.066094,0.224229

In [7]:
results['thresholds'], results['threshold_metrics'] = build_threshold_metrics(results['pred_values'])

d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)
d:\Python Projects\Hospital readmission risk\hospital_readmission_risk\models.py:290: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  thresholds[col + '_' + str(t)] = (values[col] >= t).astype(int)

       readmit_30d readmit_90d  logreg_d30_0.05  logreg_d30_0.1  \
0                0           0                1               1
1                0           0                1               1
2                0           0                1               0
4                0           0                1               0
6                0           0                1               1
...            ...         ...              ...             ...
109493           0           0                1               1
109494           0           0                1               1
109495           0           0                1               1
109496           0           0                1               1
109497           0           0                1               1

        logreg_d30_0.15  logreg_d30_0.2  logreg_d30_0.25  logreg_d30_0.3  \
0                     1               1                0               0
1                     1               0                0               0
2                     0               0                0               0
4                     0               0                0               0
6                     1               1                1               0
...                 ...             ...              ...             ...
109493                1               1                1               1
109494                1               1                1               1
109495                1               1                1               0
109496                1               1                1               1
109497                1               1                1               1

        logreg_d30_0.35  logreg_d30_0.4  ...  lightgbm_d90_0.5  \
0                     0               0  ...                 0
1                     0               0  ...                 0
2                     0               0  ...                 0
4                     0               0  ...                 0
6                     0               0  ...                 0
...                 ...             ...  ...               ...
109493                1               1  ...                 0
109494                1               1  ...                 0
109495                0               0  ...                 0
109496                1               1  ...                 0
109497                1               1  ...                 0

        lightgbm_d90_0.55  lightgbm_d90_0.6  lightgbm_d90_0.65  \
0                       0                 0                  0
1                       0                 0                  0
2                       0                 0                  0
4                       0                 0                  0
6                       0                 0                  0
...                   ...               ...                ...
109493                  0                 0                  0
109494                  0                 0                  0
109495                  0                 0                  0
109496                  0                 0                  0
109497                  0                 0                  0

        lightgbm_d90_0.7  lightgbm_d90_0.75  lightgbm_d90_0.8  \
0                      0                  0                 0
1                      0                  0                 0
2                      0                  0                 0
4                      0                  0                 0
6                      0                  0                 0
...                  ...                ...               ...
109493                 0                  0                 0
109494                 0                  0                 0
109495                 0                  0                 0
109496                 0                  0                 0
109497                 0                  0                 0

        lightgbm_d90_0.85  lightgbm_d90_0.9  lightgbm_d90_0.95
0                       0                 0                  0
1                       0                 0                  0
2                       0                 0                  0
4                       0                 0                  0
6                       0                 0                  0
...                   ...               ...                ...
109493                  0                 0                  0
109494                  0                 0                  0
109495                  0                 0                  0
109496                  0                 0                  0
109497                  0                 0                  0

[67431 rows x 116 columns]

ValueError: Classification metrics can't handle a mix of unknown and binary targets

In [8]:
results['pred_values']

,readmit_30d,readmit_90d,logreg_d30,logreg_d90,rf_d30,rf_d90,lightgbm_d30,lightgbm_d90
X,,,,,,,,
11069,0,0,0.005678,0.004387,0.000000,0.000000,0.000013,0.000021
13931,0,0,0.015351,0.012126,0.000000,0.000000,0.000019,0.000033
5367,0,0,0.002747,0.004235,0.000000,0.000000,0.000015,0.000029
5453,0,0,0.005412,0.003133,0.000000,0.000000,0.000022,0.000019
8529,0,0,0.004941,0.004783,0.000000,0.003403,0.000016,0.000020
...,...,...,...,...,...,...,...,...
42858,0,0,0.028384,0.044057,0.000000,0.000000,0.000014,0.000021
44872,0,0,0.029426,0.063021,0.000000,0.000000,0.000012,0.000017
46740,0,0,0.049907,0.106964,0.000000,0.000000,0.000016,0.000020
8941,0,0,0.011399,0.011628,0.000000,0.002746,0.000011,0.000028
56686,0,0,0.310367,0.558924,0.398624,0.630253,0.055752,0.206295

In [9]:
df_cost = cost_reduction_preprocessor(df, results['pred_values'], df_results, d30 = True)

KeyError: '[11069, 5367, 5453, 27295, 5748, 24656, 57662, 53091, 49187, 53133, 20549, 5012, 30198, 30647, 23680, 36506, 29419, 34567, 43376, 1931, 9957, 33643, 29109, 3418, 23381, 27423, 49993, 44916, 13585, 46405, 35048, 3593, 26668, 35617, 44600, 14486, 43474, 60355, 29899, 65769, 24828, 63456, 48684, 26695, 26729, 7890, 36101, 23503, 28863, 35602, 34697, 65708, 39261, 66813, 63141, 44661, 45431, 24612, 56039, 46128, 66861, 60660, 25895, 38710, 23417, 57882, 19828, 20716, 18718, 55067, 28462, 55000, 26266, 61919, 26876, 37786, 27064, 14592, 21334, 53964, 11504, 14595, 26482, 29271, 61343, 63919, 63190, 19767, 27017, 13695, 23210, 59260, 20550, 25200, 31858, 66903, 26275, 26556, 26874, 10193, 45183, 31200, 849, 66580, 45931, 53883, 37721, 56511, 13961, 35213, 1836, 55783, 30940, 61020, 53201, 25292, 8489, 54125, 67189, 34749, 26159, 9758, 64637, 29081, 28501, 2549, 48535, 66748, 35496, 3401, 34279, 24249, 59553, 60754, 23143, 44044, 46445, 37912, 40355, 27101, 17683, 34344, 33364, 36802, 27294, 20492, 34950, 52852, 5875, 58553, 65698, 55678, 35689, 43490, 30141, 24065, 28839, 5803, 26609, 47809, 35316, 3928, 57709, 47391, 15286, 37683, 37818, 62932, 28889, 39714, 39149, 22346, 29017, 20322, 53241, 54657, 50741, 27210, 45433, 31798, 53991, 57294, 28815, 1811, 48108, 37451, 13447, 2059, 57691, 11113, 3310, 34632, 54272, 51912, 32814, 61382, 27550, 21641, 37817, 29078, 57632, 55214, 35067, 44257, 12256, 39394, 36423, 35366, 13415, 61159, 37342, 61119, 26087, 25162, 64367, 13342, 54360, 52576, 26106, 50400, 24775, 60397, 6656, 5975, 54548, 39575, 34299, 24636, 63082, 63554, 33992, 28990, 10727, 42989, 63770, 30019, 38743, 35019, 66790, 4977, 48465, 66573, 49903, 54795, 24580, 30179, 20664, 63288, 55297, 26689, 50152, 21201, 29471, 19537, 58407, 3173, 66258, 25364, 39276, 60067, 37878, 55881, 27316, 27590, 36352, 37530, 38123, 3495, 4021, 52164, 22274, 49243, 42221, 26750, 27910, 51975, 39231, 37614, 7201, 41784, 26632, 27562, 1696, 37618, 24808, 39949, 24206, 32757, 27485, 39361, 28427, 35731, 14916, 35264, 36084, 38992, 43122, 44076, 37558, 25353, 34597, 9128, 34405, 20355, 66041, 38178, 30662, 22088, 44404, 63885, 25356, 25942, 2903, 26937, 48413, 3702, 39473, 62799, 60383, 1928, 9902, 27595, 15230, 66729, 50919, 62340, 37581, 37723, 35599, 24339, 44679, 67387, 23812, 31484, 24896, 55983, 35937, 6573, 24228, 36032, 12414, 36496, 47676, 3425, 34458, 53233, 25908, 65711, 34661, 34907, 13094, 34473, 26396, 66597, 64923, 49921, 14561, 35203, 48943, 35004, 11746, 10502, 45359, 20385, 40305, 35716, 53950, 35835, 24115, 27522, 29310, 24164, 35978, 34676, 26115, 46868, 29664, 37363, 25590, 57952, 65865, 38089, 54393, 59603, 34995, 51710, 59828, 64004, 30153, 12223, 27379, 66402, 50007, 54968, 51061, 52811, 38554, 4248, 34509, 37803, 26291, 51918, 60656, 253, 19762, 25418, 37140, 37454, 27558, 26826, 58694, 43475, 65148, 25696, 33042, 45854, 26164, 34913, 28509, 274, 3171, 39400, 67320, 24316, 24749, 14572, 44376, 34403, 36480, 26056, 54109, 35806, 47251, 27136, 49465, 35580, 60807, 55187, 35130, 24341, 12936, 3707, 39336, 1792, 57076, 26740, 51013, 26036, 37255, 67073, 22351, 35993, 59853, 60630, 34756, 5567, 43772, 5083, 58046, 31034, 51350, 16349, 6425, 25981, 27254, 56737, 29291, 3242, 23315, 25585, 11150, 7569, 27243, 23735, 58756, 46351, 55328, 67343, 37223, 36056, 47211, 61366, 49216, 24378, 280, 33250, 884, 21761, 59365, 8610, 12510, 29099, 66145, 56632, 64669, 66329, 1370, 11478, 59015, 17284, 37806, 45964, 31372, 7732, 59217, 39158, 61264, 12351, 52004, 54475, 47869, 50432, 35394, 7363, 35403, 39406, 22977, 66556, 27887, 26021, 34408, 55242, 33197, 27991, 35522, 28823, 43567, 26491, 6675, 14655, 49414, 35704, 457, 24418, 66817, 46529, 9146, 27325, 31291, 36332, 3382, 27681, 7891, 7267, 34834, 23480, 9889, 65133, 54902, 33328, 32075, 5199, 44561, 31336, 42716, 11821, 35211, 24275, 30323, 27166, 3580, 17537, 24445, 40829, 34762, 26242, 48450, 46492, 57310, 4364, 3437, 27984, 33797, 12038, 26034, 5537, 31640, 27225, 42400, 1480, 1477, 60359, 55763, 35054, 37810, 26815, 3635, 7431, 61522, 29034, 42973, 25889, 26023, 35768, 44944, 26463, 25806, 67002, 1570, 67070, 2180, 23330, 63706, 38983, 33904, 39297, 55323, 49663, 30787, 21393, 20657, 65959, 7055, 66895, 55491, 65983, 37047, 54562, 24234, 42329, 20458, 22775, 29795, 12335, 15165, 19948, 45321, 24131, 26725, 50788, 59185, 40754, 50199, 31911, 44177, 14477, 56107, 45919, 29085, 27972, 62004, 32417, 9126, 54806, 24793, 36459, 35202, 48116, 26341, 49168, 49468, 66840, 13373, 52802, 25153, 26890, 36070, 60349, 6627, 34664, 23801, 58170, 27989, 55238, 15152, 22181, 36246, 7713, 34895, 46696, 35480, 26744, 44444, 27234, 34444, 46770, 3292, 11993, 35498, 39416, 56146, 54447, 52187, 48859, 47397, 52036, 14731, 56580, 39634, 65803, 35350, 46859, 23994, 62294, 20974, 24706, 26231, 33334, 1795, 42178, 6194, 38989, 44002, 19496, 13964, 52741, 1985, 61599, 7842, 1734, 11209, 54635, 65986, 28503, 44090, 35647, 22472, 67079, 26795, 45694, 3288, 66578, 43974, 50664, 64519, 38891, 40977, 13802, 54658, 1400, 10359, 43699, 20743, 42646, 25674, 54925, 62141, 37783, 1897, 23785, 51694, 36063, 57322, 42700, 26357, 52001, 27395, 49433, 29920, 26089, 9856, 56581, 29013, 42740, 36548, 61364, 60016, 58733, 27202, 20873, 48992, 22249, 62399, 42526, 66500, 63822, 26529, 12562, 29391, 11607, 28814, 34475, 24352, 61730, 59468, 25541, 54982, 52259, 62695, 42666, 65526, 53927, 1736, 28852, 36264, 66112, 29088, 63107, 23727, 63750, 43887, 53021, 34388, 8504, 7168, 8395, 27439, 31970, 54053, 30243, 47400, 29276, 51577, 6497, 34774, 48705, 44595, 1491, 8364, 29905, 43595, 34679, 61729, 26851, 44800, 54566, 35237, 35068, 17547, 6199, 12421, 54825, 48576, 25067, 34357, 28733, 24211, 24598, 30115, 34590, 26031, 32684, 43256, 22544, 63369, 24458, 43641, 37970, 65868, 11348, 26406, 21394, 38004, 13337, 46605, 50881, 54357, 39109, 37365, 40248, 27533, 66750, 53381, 34367, 34760, 59786, 49443, 20318, 1574, 67228, 55652, 3601, 35593, 6692, 66541, 52810, 8073, 35217, 30546, 32306, 46051, 697, 1941, 53399, 13670, 66163, 51217, 58432, 26195, 35873, 54768, 24438, 31762, 61574, 53277, 66679, 6498, 19524, 23865, 54466, 29947, 62324, 54677, 43523, 34879, 25907, 64926, 29624, 33239, 59331, 39493, 63854, 28808, 59030, 38993, 24891, 13451, 3502, 30481, 34859, 43905, 24620, 2132, 60425, 43508, 3660, 26318, 8197, 35945, 32760, 12774, 48195, 12662, 22292, 66194, 54328, 54896, 31931, 65418, 3272, 3757, 4442, 63925, 13010, 51218, 58886, 47389, 27422, 66841, 27611, 54059, 66263, 66173, 1879, 41306, 26496, 39106, 24478, 33462, 37994, 3700, 39510, 57218, 29102, 12273, 28958, 55665, 45589, 48663, 39381, 36309, 3394, 37870, 34855, 32978, 67310, 36411, 54755, 36006, 58476, 30950, 45274, 43431, 6685, 7912, 39533, 52809, 60416, 33344, 3427, 29214, 49828, 9396, 11296, 1655, 51891, 45061, 61914, 45029, 21666, 65089, 61072, 39782, 66515, 2791, 56636, 29876, 6682, 33003, 66462, 37332, 37652, 1413, 20864, 55791, 10290, 51505, 13671, 41234, 1486, 60406, 60764, 21000, 23534, 29596, 43749, 35697, 47178, 29196, 65857, 26184, 47635, 5598, 11466, 19414, 65756, 24646, 35796, 63994, 40377, 26923, 32701, 54308, 24848, 45666, 51829, 3431, 66222, 34791, 54873, 34988, 35648, 24777, 42854, 54342, 49348, 37799, 12791, 66272, 36629, 28058, 41943, 61775, 20624, 54980, 53215, 51337, 24567, 39813, 39257, 29915, 36138, 54799, 54025, 27980, 1641, 39315, 22503, 59286, 8740, 26772, 27985, 60034, 23175, 47909, 35753, 65159, 42181, 24414, 45182, 27054, 31463, 48730, 29260, 22177, 9897, 57382, 32475, 53064, 12284, 49100, 26476, 13159, 6672, 40268, 64860, 54914, 35976, 39126, 26288, 66867, 66400, 37510, 12964, 43293, 13504, 20777, 30994, 66330, 26779, 24906, 46248, 29275, 59233, 35636, 6676, 54292, 1603, 29244, 61089, 5625, 1463, 1784, 34619, 30965, 58124, 24629, 55032, 55291, 35182, 37957, 34317, 49852, 23783, 6013, 12139, 36033, 1956, 25986, 39387, 63481, 25623, 67289, 51964, 27373, 43819, 9928, 56145, 26064, 36058, 56874, 40918, 26018, 25503, 66211, 22997, 46630, 54298, 1602, 28282, 1288, 9987, 35033, 66869, 49352, 62701, 7318, 66474, 54960, 23920, 29463, 1523, 6501, 31751, 27436, 59815, 34102, 3304, 34792, 64995, 25660, 57668, 66529, 35715, 10527, 26791, 5982, 48557, 47016, 46342, 1671, 27308, 25798, 55260, 2499, 42855, 42284, 42985, 52303, 5859, 6211, 26332, 35696, 46487, 27682, 13845, 47633, 50478, 67347, 63691, 55348, 42650, 36242, 62307, 30629, 52365, 6689, 539, 26818, 26915, 66347, 5491, 22029, 35721, 25736, 51481, 55773, 66075, 14875, 34646, 3222, 43638, 28510, 14212, 60676, 8607, 50371, 34423, 59962, 25586, 32540, 67284, 57397, 43865, 3694, 2060, 39480, 2046, 35856, 47988, 66914, 48594, 45198, 65707, 3313, 35166, 23378, 20889, 35153, 24200, 34982, 7947, 54046, 12079, 35263, 9093, 26276, 57695, 36520, 35746, 23005, 53216, 20757, 24701, 60228, 29201, 21558, 64145, 13561, 57060, 44027, 35458, 2360, 58725, 5862, 53095, 26213, 12967, 14615, 58927, 30526, 48673, 25668, 50549, 37111, 47611, 14467, 19051, 6748, 27292, 63366, 22255, 45595, 66271, 54539, 26706, 25423, 25101, 65704, 58915, 25374, 24304, 10088, 28396, 15074, 37807, 23239, 35379, 36151, 3265, 57038, 19219, 3647, 26371, 66046, 48864, 19770, 5771, 34201, 9057, 34978, 29457, 66254, 34955, 39296, 49057, 33698, 38081, 27693, 38671, 30230, 59648, 3645, 1689, 54890, 43394, 195, 31718, 37889, 34894, 54877, 35815, 5528, 29638, 21064, 14603, 44822, 46150, 59927, 12423, 17823, 3624, 6757, 10186, 61863, 51253, 4472, 55274, 25340, 66619, 46055, 44086, 62865, 51324, 55793, 37172, 37877, 56464, 55714, 36462, 34538, 5436, 1743, 35325, 30748, 6936, 52830, 24929, 45840, 54174, 39258, 10080, 63074, 21268, 34209, 25885, 64207, 54961, 67014, 3270, 30395, 35520, 25646, 43320, 21379, 3231, 1503, 53900, 1618, 15215, 13643, 47212, 1638, 35469, 34901, 66559, 32621, 34264, 29606, 47149, 12354, 28300, 35357, 5779, 23145, 50633, 33384, 25562, 11141, 66089, 29226, 1584, 20279, 27415, 24753, 66851, 58521, 1679, 52808, 14614, 61452, 49869, 55632, 63881, 776, 66785, 53340, 26450, 36050, 24847, 53191, 26377, 31916, 35372, 59934, 22871, 27119, 8416, 3585, 48498, 50588, 58378, 37546, 57893, 45965, 14881, 12535, 66321, 24381, 39013, 27458, 31677, 39187, 34667, 21396, 61424, 36425, 66901, 37444, 45585, 35404, 50827, 34883, 62300, 46594, 64280, 49405, 25911, 1507, 59881, 60211, 29864, 50824, 44633, 10099, 26131, 6061, 34287, 55264, 29177, 27221, 67367, 51646, 27443, 28966, 64201, 9954, 37906, 59537, 21590, 47273, 35432, 39245, 29138, 26758, 20188, 29043, 7390, 61649, 5265, 65175, 53593, 26847, 35058, 34302, 27448, 16458, 469, 14225, 24573, 29016, 3461, 39859, 41747, 19780, 25697, 59684, 14488, 29094, 42906, 1319, 29020, 13524, 42777, 6975, 36438, 27705, 59016, 49889, 41709, 8557, 7161, 6075, 29474, 35882, 59514, 53079, 36461, 23262, 43483, 37839, 3184, 9620, 26860, 60705, 17779, 24112, 39166, 13757, 37149, 11306, 54152, 25732, 65376, 35511, 5342, 10887, 53003, 36384, 45501, 28701, 19736, 42682, 50157, 2125, 66853, 58320, 27342, 24621, 21109, 23342, 26780, 3738, 30468, 46504, 35896, 22269, 26218, 29149, 26072, 52848, 681, 15127, 45795, 28937, 24784, 65105, 41586, 54879, 36165, 26680, 37613, 54177, 63917, 51954, 34921, 39270, 36362, 46987, 66032, 34496, 27270, 54543, 24521, 48121, 6541, 27252, 26236, 58367, 53892, 65141, 54564, 29331, 47108, 27063, 54949, 66657, 28983, 54841, 13352, 21805, 8006, 29262, 12141, 37625, 729, 3416, 36886, 39252, 42497, 14154, 3994, 39415, 7359, 27251, 55669, 47092, 28802, 50902, 34453, 19621, 65935, 35494, 20280, 57180, 11400, 35307, 47146, 54647, 35269, 30390, 26059, 37476, 66456, 37678, 6946, 47035, 36261, 454, 26684, 26158, 54315, 62935, 32106, 45847, 55372, 24168, 30735, 25974, 65439, 39154, 34557, 29234, 29215, 9155, 60419, 65709, 18988, 63717, 52883, 25691, 39379, 36376, 62393, 33016, 24755, 55225, 35359, 37453, 23573, 66685, 55545, 47187, 35327, 54626, 37362, 51961, 33838, 61469, 3753, 26577, 50143, 66890, 37343, 24705, 59262, 29568, 67328, 36256, 3214, 66611, 1978, 34439, 65235, 49207, 65812, 46046, 14499, 3615, 25466, 26404, 24165, 47642, 39445, 53186, 24590, 26837, 35837, 26760, 35750, 25182, 34686, 27344, 27092, 51277, 9645, 39230, 27665, 64224, 37248, 24171, 41325, 26151, 31724, 30704, 44967, 28009, 67269, 47290, 31049, 63931, 56259, 64719, 49937, 49618, 58896, 31868, 3229, 23288, 27362, 59674, 61115, 22910, 24780, 61256, 66627, 59810, 29363, 34776, 35387, 42584, 27401, 20057, 34871, 26344, 62922, 23981, 26803, 37264, 37254, 58682, 28819, 27434, 9163, 30555, 5795, 36177, 55293, 65074, 26202, 64349, 31450, 15110, 55321, 60549, 430, 67406, 27179, 36128, 54719, 20419, 41061, 21317, 26133, 51764, 63137, 65818, 22376, 54226, 52374, 34539, 48653, 66736, 14136, 3473, 11402, 30156, 66966, 29453, 47840, 3732, 39418, 53230, 50237, 65976, 20412, 48712, 29207, 25863, 65719, 28631, 66982, 28292, 10595, 50666, 44490, 46251, 37188, 3735, 59457, 50002, 37319, 30578, 10127, 38991, 25450, 12257, 39511, 29210, 36414, 27554, 47004, 40435, 12913, 66873, 39330, 67069, 29005, 15274, 5382, 63075, 35787, 39626, 36351, 3263, 66730, 37144, 49760, 22130, 27059, 48626, 43807, 26775, 38552, 1566, 27417, 33278, 66142, 24439, 20292, 41102, 22691, 24579, 31464, 24748, 62778, 58052, 26262, 52713, 25608, 26211, 54379, 63504, 35998, 36360, 2982, 5438, 51181, 52695, 5762, 24247, 39494, 47312, 23432, 65802, 26484, 45937, 10089, 66304, 45218, 12353, 34780, 27129, 14487, 6234, 31757, 23879, 32344, 25928, 29042, 35683, 417, 34983, 32555, 54490, 29502, 41487, 48528, 9019, 34061, 34891, 35020, 48935, 21100, 66624, 26192, 35311, 39414, 24337, 30149, 57780, 66325, 10741, 49706, 34999, 32395, 42579, 34951, 34014, 22178, 19609, 39237, 65793, 42971, 9317, 50254, 26538, 27645, 37325, 26981, 66713, 63584, 34965, 61661, 66711, 49266, 52569, 56909, 28296, 29037, 60503, 51911, 24145, 35378, 39401, 55104, 49734, 48862, 65987, 2086, 44926, 64117, 39407, 33423, 52891, 45777, 65304, 13287, 54924, 2522, 26516, 19832, 7545, 16451, 61818, 45132, 28339, 54892, 43176, 37868, 35299, 25984, 24452, 28928, 45776, 47949, 47868, 52298, 20072, 51894, 35822, 49440, 59535, 29221, 26346, 1744, 65423, 35927, 13737, 66305, 26271, 53989, 6945, 29147, 9998, 29065, 32630, 50648, 48607, 24075, 26191, 20248, 896, 686, 28826, 50209, 7327, 31234, 1092, 30095, 63438, 63170, 25680, 46794, 20005, 35734, 61451, 26383, 57496, 39457, 26588, 9590, 25265, 52803, 43384, 66749, 54697, 28951, 22896, 67225, 5576, 50796, 3861, 24674, 54741, 37771, 25578, 37238, 46048, 35679, 23339, 1970, 33524, 53708, 65695, 30047, 29145, 55555, 53105, 9459, 57770, 27479, 29792, 3396, 6280, 39413, 61751, 49270, 3279, 37135, 24863, 31316, 37431, 61650, 54594, 8279, 26215, 61471, 28178, 24638, 19927, 39160, 35015, 3698, 49014, 34219, 6545, 23025, 29771, 66596, 64284, 9817, 59280, 58206, 1718, 46528, 34365, 52989, 35114, 14111, 55537, 65934, 27363, 35544, 64570, 3714, 14165, 33958, 55524, 34134, 13124, 24376, 26101, 25210, 26840, 34508, 25796, 31274, 34321, 33049, 35189, 35538, 49404, 35880, 22239, 33730, 4391, 36319, 19890, 66241, 5148, 3189, 47919, 46481, 59328, 24912, 54988, 20489, 35915, 29338, 3388, 19501, 15364, 44162, 67026, 58852, 54979, 13564, 51896, 1580, 45598, 32392, 27117, 46440, 3433, 43851, 54941, 20237, 55062, 35074, 23738, 25794, 35274, 62817, 33068, 20602, 50454, 67008, 26422, 6049, 29266, 5633, 35762, 39508, 25872, 31744, 35624, 26554, 39403, 12954, 1632, 29258, 66346, 27613, 52322, 26523, 26700, 52035, 5444, 48728, 6128, 35487, 31771, 5048, 24461, 31045, 28895, 42457, 35981, 6006, 26168, 63514, 38009, 53154, 54983, 57809, 66674, 27646, 53151, 54071, 26185, 66769, 27137, 26063, 33600, 3519, 61718, 3584, 31442, 27309, 54669, 45979, 37442, 34104, 18488, 34989, 29406, 41682, 57396, 63219, 62395, 52363, 37478, 24455, 51668, 37369, 6166, 66886, 1490, 28985, 46164, 29308, 2020, 3758, 5785, 26517, 36164, 35082, 57366, 29298, 29353, 34936, 4465, 33450, 46006, 45754, 1967, 57343, 64928, 5568, 37087, 31149, 35598, 35041, 35501, 20969, 7091, 29390, 34391, 55704, 24460, 11527, 25725, 47023, 55695, 9731, 30525, 27080, 1484, 34548, 34436, 49301, 24602, 10925, 51950, 29014, 22497, 231, 50289, 25284, 61110, 25248, 62766, 65903, 39376, 3638, 24867, 66722, 12694, 1572, 66129, 20268, 35164, 31191, 39260, 27089, 26805, 64491, 25424, 29903, 265, 647, 30891, 66382, 14355, 65889, 27287, 14613, 26495, 25065, 3445, 39517, 28195, 38234, 39498, 19997, 64122, 37181, 29490, 45369, 55947, 59029, 22252, 33247, 9462, 55133, 56370, 26510, 29509, 34278, 65936, 13519, 54305, 44048, 4749, 32838, 46119, 36010, 37731, 22194, 6311, 30094, 39050, 56615, 39525, 30150, 50913, 44580, 38956, 33875, 63992, 7635, 56500, 24103, 29117, 37831, 23158, 31173, 32414, 25415, 65366, 45250, 65916, 30424, 65937, 16162, 53265, 4618, 24385, 57334, 2417, 25876, 36419, 66389, 3393, 67285, 37691, 26949, 59190, 35723, 65908, 33056, 22652, 59443, 25913, 24350, 66608, 7752, 59351, 55969, 1666, 63934, 36471, 35664, 64496, 47344, 35090, 34876, 54498, 42179, 39364, 32153, 6871, 29173, 34655, 50244, 28870, 39399, 13839, 24710, 14514, 59690, 47431, 14300, 32777, 41879, 30249, 26530, 25250, 59137, 58825, 39232, 24457, 6974, 35407, 51457, 42796, 5201, 11484, 57614, 53032, 36314, 35027, 48379, 60168, 26458, 29448, 52753, 50175, 29096, 54717, 61069, 21667, 58073, 20988, 664, 55397, 35257, 12052, 24257, 33023, 26786, 27327, 35581, 25999, 5751, 38054, 67031, 29170, 37539, 6986, 50709, 52379, 33657, 16159, 31582, 56730, 27259, 24126, 47062, 48227, 25492, 27534, 54882, 24593, 36283, 46741, 54618, 37287, 35914, 59218, 2069, 37281, 50646, 28827, 29392, 66183, 20367, 29106, 60330, 18967, 49340, 25768, 31648, 22085, 32339, 63371, 45300, 34981, 66546, 50008, 45822, 21456, 16100, 24712, 2593, 12432, 29064, 29322, 3508, 2532, 55743, 35541, 39487, 63622, 33465, 9924, 20499, 56611, 55769, 36225, 29618, 24176, 54051, 17712, 11359, 19837, 22636, 2065, 40913, 6418, 1846, 22818, 35951, 45574, 9025, 29736, 1793, 57220, 26053, 26198, 34402, 51741, 25723, 35106, 23638, 44963, 52618, 36140, 27615, 37277, 36204, 39442, 3467, 54126, 49843, 66200, 52687, 54862, 57564, 36473, 44212, 52878, 4653, 26001, 35280, 60975, 38195, 63995, 27438, 39167, 21525, 36149, 46906, 27902, 63709, 43159, 10460, 44773, 28485, 3334, 14619, 28236, 61768, 14313, 21197, 34015, 26594, 50776, 17714, 53992, 53978, 13202, 61395, 38994, 27600, 24391, 66583, 44875, 55681, 63672, 67314, 29731, 51312, 34797, 34778, 23367, 29051, 26433, 39431, 39067, 4243, 66327, 47030, 46375, 3493, 24407, 20665, 2089, 53023, 67400, 64913, 51094, 39703, 28945, 56252, 67292, 19808, 36340, 49091, 604, 24880, 55699, 35695, 27218, 39247, 25376, 20332, 11910, 55760, 63522, 47568, 34843, 18593, 35410, 22613, 46981, 24738, 28098, 51945, 52936, 59390, 37932, 7920, 42587, 25285, 66911, 34, 55344, 44051, 756, 34598, 22882, 24856, 9769, 44509, 53454, 29031, 22848, 19413, 54583, 20807, 57869, 35759, 60861, 66369, 6059, 54402, 43536, 27480, 26351, 59021, 38604, 39295, 11980, 3697, 4421, 21046, 39283, 21361, 67271, 24166, 52408, 35893, 33421, 25867, 35638, 26126, 20768, 66333, 66999, 35415, 28883, 66282, 28266, 49408, 26533, 49739, 65999, 1731, 26214, 44861, 9350, 28579, 59521, 24548, 49269, 36447, 26628, 50195, 51419, 3248, 43976, 7264, 34953, 36276, 45846, 12111, 5920, 37717, 20813, 49066, 26304, 341, 39528, 34739, 12252, 23166, 11048, 13141, 54405, 22362, 29500, 66407, 29141, 25029, 59247, 42960, 35795, 25983, 24157, 45962, 55362, 57373, 8264, 46791, 20718, 1483, 53397, 62356, 39523, 22125, 53122, 14644, 46441, 20276, 28125, 13525, 10791, 7328, 23825, 37843, 5370, 34419, 49342, 11983, 43537, 23609, 64075, 36239, 29335, 32482, 39186, 50401, 60580, 26311, 23754, 37557, 32507, 57997, 64561, 19759, 37698, 66335, 29514, 8075, 13905, 26097, 37560, 31088, 1670, 44534, 13797, 33761, 23008, 65810, 5784, 45023, 34358, 19578, 11262, 47835, 28886, 49121, 39371, 26574, 33473, 38876, 66616, 57839, 42852, 35968, 22397, 26904, 745, 58308, 42686, 34181, 34751, 34827, 43432, 57250, 35376, 36311, 44560, 67227, 38589, 20109, 26182, 37507, 59683, 64670, 28347, 65352, 34399, 37562, 57161, 25588, 58719, 32614, 35600, 926, 35484, 26305, 46793, 9738, 19597, 32226, 59161

In [ ]:
gains = estimate_cost_reduction(df_cost, results['pred_values'], results['thresholds'])

In [10]:
rows = results['pred_values'].index
cols = ['stay_id','cost_per_day_stay','total_readmission_cost','avg_cost_of_prev_stays']
boo = df.loc[rows][cols].copy()

boo['readmit_' + '30d'] = df_results.loc[rows, 'readmit_' + '30d']

KeyError: '[11069, 5367, 5453, 27295, 5748, 24656, 57662, 53091, 49187, 53133, 20549, 5012, 30198, 30647, 23680, 36506, 29419, 34567, 43376, 1931, 9957, 33643, 29109, 3418, 23381, 27423, 49993, 44916, 13585, 46405, 35048, 3593, 26668, 35617, 44600, 14486, 43474, 60355, 29899, 65769, 24828, 63456, 48684, 26695, 26729, 7890, 36101, 23503, 28863, 35602, 34697, 65708, 39261, 66813, 63141, 44661, 45431, 24612, 56039, 46128, 66861, 60660, 25895, 38710, 23417, 57882, 19828, 20716, 18718, 55067, 28462, 55000, 26266, 61919, 26876, 37786, 27064, 14592, 21334, 53964, 11504, 14595, 26482, 29271, 61343, 63919, 63190, 19767, 27017, 13695, 23210, 59260, 20550, 25200, 31858, 66903, 26275, 26556, 26874, 10193, 45183, 31200, 849, 66580, 45931, 53883, 37721, 56511, 13961, 35213, 1836, 55783, 30940, 61020, 53201, 25292, 8489, 54125, 67189, 34749, 26159, 9758, 64637, 29081, 28501, 2549, 48535, 66748, 35496, 3401, 34279, 24249, 59553, 60754, 23143, 44044, 46445, 37912, 40355, 27101, 17683, 34344, 33364, 36802, 27294, 20492, 34950, 52852, 5875, 58553, 65698, 55678, 35689, 43490, 30141, 24065, 28839, 5803, 26609, 47809, 35316, 3928, 57709, 47391, 15286, 37683, 37818, 62932, 28889, 39714, 39149, 22346, 29017, 20322, 53241, 54657, 50741, 27210, 45433, 31798, 53991, 57294, 28815, 1811, 48108, 37451, 13447, 2059, 57691, 11113, 3310, 34632, 54272, 51912, 32814, 61382, 27550, 21641, 37817, 29078, 57632, 55214, 35067, 44257, 12256, 39394, 36423, 35366, 13415, 61159, 37342, 61119, 26087, 25162, 64367, 13342, 54360, 52576, 26106, 50400, 24775, 60397, 6656, 5975, 54548, 39575, 34299, 24636, 63082, 63554, 33992, 28990, 10727, 42989, 63770, 30019, 38743, 35019, 66790, 4977, 48465, 66573, 49903, 54795, 24580, 30179, 20664, 63288, 55297, 26689, 50152, 21201, 29471, 19537, 58407, 3173, 66258, 25364, 39276, 60067, 37878, 55881, 27316, 27590, 36352, 37530, 38123, 3495, 4021, 52164, 22274, 49243, 42221, 26750, 27910, 51975, 39231, 37614, 7201, 41784, 26632, 27562, 1696, 37618, 24808, 39949, 24206, 32757, 27485, 39361, 28427, 35731, 14916, 35264, 36084, 38992, 43122, 44076, 37558, 25353, 34597, 9128, 34405, 20355, 66041, 38178, 30662, 22088, 44404, 63885, 25356, 25942, 2903, 26937, 48413, 3702, 39473, 62799, 60383, 1928, 9902, 27595, 15230, 66729, 50919, 62340, 37581, 37723, 35599, 24339, 44679, 67387, 23812, 31484, 24896, 55983, 35937, 6573, 24228, 36032, 12414, 36496, 47676, 3425, 34458, 53233, 25908, 65711, 34661, 34907, 13094, 34473, 26396, 66597, 64923, 49921, 14561, 35203, 48943, 35004, 11746, 10502, 45359, 20385, 40305, 35716, 53950, 35835, 24115, 27522, 29310, 24164, 35978, 34676, 26115, 46868, 29664, 37363, 25590, 57952, 65865, 38089, 54393, 59603, 34995, 51710, 59828, 64004, 30153, 12223, 27379, 66402, 50007, 54968, 51061, 52811, 38554, 4248, 34509, 37803, 26291, 51918, 60656, 253, 19762, 25418, 37140, 37454, 27558, 26826, 58694, 43475, 65148, 25696, 33042, 45854, 26164, 34913, 28509, 274, 3171, 39400, 67320, 24316, 24749, 14572, 44376, 34403, 36480, 26056, 54109, 35806, 47251, 27136, 49465, 35580, 60807, 55187, 35130, 24341, 12936, 3707, 39336, 1792, 57076, 26740, 51013, 26036, 37255, 67073, 22351, 35993, 59853, 60630, 34756, 5567, 43772, 5083, 58046, 31034, 51350, 16349, 6425, 25981, 27254, 56737, 29291, 3242, 23315, 25585, 11150, 7569, 27243, 23735, 58756, 46351, 55328, 67343, 37223, 36056, 47211, 61366, 49216, 24378, 280, 33250, 884, 21761, 59365, 8610, 12510, 29099, 66145, 56632, 64669, 66329, 1370, 11478, 59015, 17284, 37806, 45964, 31372, 7732, 59217, 39158, 61264, 12351, 52004, 54475, 47869, 50432, 35394, 7363, 35403, 39406, 22977, 66556, 27887, 26021, 34408, 55242, 33197, 27991, 35522, 28823, 43567, 26491, 6675, 14655, 49414, 35704, 457, 24418, 66817, 46529, 9146, 27325, 31291, 36332, 3382, 27681, 7891, 7267, 34834, 23480, 9889, 65133, 54902, 33328, 32075, 5199, 44561, 31336, 42716, 11821, 35211, 24275, 30323, 27166, 3580, 17537, 24445, 40829, 34762, 26242, 48450, 46492, 57310, 4364, 3437, 27984, 33797, 12038, 26034, 5537, 31640, 27225, 42400, 1480, 1477, 60359, 55763, 35054, 37810, 26815, 3635, 7431, 61522, 29034, 42973, 25889, 26023, 35768, 44944, 26463, 25806, 67002, 1570, 67070, 2180, 23330, 63706, 38983, 33904, 39297, 55323, 49663, 30787, 21393, 20657, 65959, 7055, 66895, 55491, 65983, 37047, 54562, 24234, 42329, 20458, 22775, 29795, 12335, 15165, 19948, 45321, 24131, 26725, 50788, 59185, 40754, 50199, 31911, 44177, 14477, 56107, 45919, 29085, 27972, 62004, 32417, 9126, 54806, 24793, 36459, 35202, 48116, 26341, 49168, 49468, 66840, 13373, 52802, 25153, 26890, 36070, 60349, 6627, 34664, 23801, 58170, 27989, 55238, 15152, 22181, 36246, 7713, 34895, 46696, 35480, 26744, 44444, 27234, 34444, 46770, 3292, 11993, 35498, 39416, 56146, 54447, 52187, 48859, 47397, 52036, 14731, 56580, 39634, 65803, 35350, 46859, 23994, 62294, 20974, 24706, 26231, 33334, 1795, 42178, 6194, 38989, 44002, 19496, 13964, 52741, 1985, 61599, 7842, 1734, 11209, 54635, 65986, 28503, 44090, 35647, 22472, 67079, 26795, 45694, 3288, 66578, 43974, 50664, 64519, 38891, 40977, 13802, 54658, 1400, 10359, 43699, 20743, 42646, 25674, 54925, 62141, 37783, 1897, 23785, 51694, 36063, 57322, 42700, 26357, 52001, 27395, 49433, 29920, 26089, 9856, 56581, 29013, 42740, 36548, 61364, 60016, 58733, 27202, 20873, 48992, 22249, 62399, 42526, 66500, 63822, 26529, 12562, 29391, 11607, 28814, 34475, 24352, 61730, 59468, 25541, 54982, 52259, 62695, 42666, 65526, 53927, 1736, 28852, 36264, 66112, 29088, 63107, 23727, 63750, 43887, 53021, 34388, 8504, 7168, 8395, 27439, 31970, 54053, 30243, 47400, 29276, 51577, 6497, 34774, 48705, 44595, 1491, 8364, 29905, 43595, 34679, 61729, 26851, 44800, 54566, 35237, 35068, 17547, 6199, 12421, 54825, 48576, 25067, 34357, 28733, 24211, 24598, 30115, 34590, 26031, 32684, 43256, 22544, 63369, 24458, 43641, 37970, 65868, 11348, 26406, 21394, 38004, 13337, 46605, 50881, 54357, 39109, 37365, 40248, 27533, 66750, 53381, 34367, 34760, 59786, 49443, 20318, 1574, 67228, 55652, 3601, 35593, 6692, 66541, 52810, 8073, 35217, 30546, 32306, 46051, 697, 1941, 53399, 13670, 66163, 51217, 58432, 26195, 35873, 54768, 24438, 31762, 61574, 53277, 66679, 6498, 19524, 23865, 54466, 29947, 62324, 54677, 43523, 34879, 25907, 64926, 29624, 33239, 59331, 39493, 63854, 28808, 59030, 38993, 24891, 13451, 3502, 30481, 34859, 43905, 24620, 2132, 60425, 43508, 3660, 26318, 8197, 35945, 32760, 12774, 48195, 12662, 22292, 66194, 54328, 54896, 31931, 65418, 3272, 3757, 4442, 63925, 13010, 51218, 58886, 47389, 27422, 66841, 27611, 54059, 66263, 66173, 1879, 41306, 26496, 39106, 24478, 33462, 37994, 3700, 39510, 57218, 29102, 12273, 28958, 55665, 45589, 48663, 39381, 36309, 3394, 37870, 34855, 32978, 67310, 36411, 54755, 36006, 58476, 30950, 45274, 43431, 6685, 7912, 39533, 52809, 60416, 33344, 3427, 29214, 49828, 9396, 11296, 1655, 51891, 45061, 61914, 45029, 21666, 65089, 61072, 39782, 66515, 2791, 56636, 29876, 6682, 33003, 66462, 37332, 37652, 1413, 20864, 55791, 10290, 51505, 13671, 41234, 1486, 60406, 60764, 21000, 23534, 29596, 43749, 35697, 47178, 29196, 65857, 26184, 47635, 5598, 11466, 19414, 65756, 24646, 35796, 63994, 40377, 26923, 32701, 54308, 24848, 45666, 51829, 3431, 66222, 34791, 54873, 34988, 35648, 24777, 42854, 54342, 49348, 37799, 12791, 66272, 36629, 28058, 41943, 61775, 20624, 54980, 53215, 51337, 24567, 39813, 39257, 29915, 36138, 54799, 54025, 27980, 1641, 39315, 22503, 59286, 8740, 26772, 27985, 60034, 23175, 47909, 35753, 65159, 42181, 24414, 45182, 27054, 31463, 48730, 29260, 22177, 9897, 57382, 32475, 53064, 12284, 49100, 26476, 13159, 6672, 40268, 64860, 54914, 35976, 39126, 26288, 66867, 66400, 37510, 12964, 43293, 13504, 20777, 30994, 66330, 26779, 24906, 46248, 29275, 59233, 35636, 6676, 54292, 1603, 29244, 61089, 5625, 1463, 1784, 34619, 30965, 58124, 24629, 55032, 55291, 35182, 37957, 34317, 49852, 23783, 6013, 12139, 36033, 1956, 25986, 39387, 63481, 25623, 67289, 51964, 27373, 43819, 9928, 56145, 26064, 36058, 56874, 40918, 26018, 25503, 66211, 22997, 46630, 54298, 1602, 28282, 1288, 9987, 35033, 66869, 49352, 62701, 7318, 66474, 54960, 23920, 29463, 1523, 6501, 31751, 27436, 59815, 34102, 3304, 34792, 64995, 25660, 57668, 66529, 35715, 10527, 26791, 5982, 48557, 47016, 46342, 1671, 27308, 25798, 55260, 2499, 42855, 42284, 42985, 52303, 5859, 6211, 26332, 35696, 46487, 27682, 13845, 47633, 50478, 67347, 63691, 55348, 42650, 36242, 62307, 30629, 52365, 6689, 539, 26818, 26915, 66347, 5491, 22029, 35721, 25736, 51481, 55773, 66075, 14875, 34646, 3222, 43638, 28510, 14212, 60676, 8607, 50371, 34423, 59962, 25586, 32540, 67284, 57397, 43865, 3694, 2060, 39480, 2046, 35856, 47988, 66914, 48594, 45198, 65707, 3313, 35166, 23378, 20889, 35153, 24200, 34982, 7947, 54046, 12079, 35263, 9093, 26276, 57695, 36520, 35746, 23005, 53216, 20757, 24701, 60228, 29201, 21558, 64145, 13561, 57060, 44027, 35458, 2360, 58725, 5862, 53095, 26213, 12967, 14615, 58927, 30526, 48673, 25668, 50549, 37111, 47611, 14467, 19051, 6748, 27292, 63366, 22255, 45595, 66271, 54539, 26706, 25423, 25101, 65704, 58915, 25374, 24304, 10088, 28396, 15074, 37807, 23239, 35379, 36151, 3265, 57038, 19219, 3647, 26371, 66046, 48864, 19770, 5771, 34201, 9057, 34978, 29457, 66254, 34955, 39296, 49057, 33698, 38081, 27693, 38671, 30230, 59648, 3645, 1689, 54890, 43394, 195, 31718, 37889, 34894, 54877, 35815, 5528, 29638, 21064, 14603, 44822, 46150, 59927, 12423, 17823, 3624, 6757, 10186, 61863, 51253, 4472, 55274, 25340, 66619, 46055, 44086, 62865, 51324, 55793, 37172, 37877, 56464, 55714, 36462, 34538, 5436, 1743, 35325, 30748, 6936, 52830, 24929, 45840, 54174, 39258, 10080, 63074, 21268, 34209, 25885, 64207, 54961, 67014, 3270, 30395, 35520, 25646, 43320, 21379, 3231, 1503, 53900, 1618, 15215, 13643, 47212, 1638, 35469, 34901, 66559, 32621, 34264, 29606, 47149, 12354, 28300, 35357, 5779, 23145, 50633, 33384, 25562, 11141, 66089, 29226, 1584, 20279, 27415, 24753, 66851, 58521, 1679, 52808, 14614, 61452, 49869, 55632, 63881, 776, 66785, 53340, 26450, 36050, 24847, 53191, 26377, 31916, 35372, 59934, 22871, 27119, 8416, 3585, 48498, 50588, 58378, 37546, 57893, 45965, 14881, 12535, 66321, 24381, 39013, 27458, 31677, 39187, 34667, 21396, 61424, 36425, 66901, 37444, 45585, 35404, 50827, 34883, 62300, 46594, 64280, 49405, 25911, 1507, 59881, 60211, 29864, 50824, 44633, 10099, 26131, 6061, 34287, 55264, 29177, 27221, 67367, 51646, 27443, 28966, 64201, 9954, 37906, 59537, 21590, 47273, 35432, 39245, 29138, 26758, 20188, 29043, 7390, 61649, 5265, 65175, 53593, 26847, 35058, 34302, 27448, 16458, 469, 14225, 24573, 29016, 3461, 39859, 41747, 19780, 25697, 59684, 14488, 29094, 42906, 1319, 29020, 13524, 42777, 6975, 36438, 27705, 59016, 49889, 41709, 8557, 7161, 6075, 29474, 35882, 59514, 53079, 36461, 23262, 43483, 37839, 3184, 9620, 26860, 60705, 17779, 24112, 39166, 13757, 37149, 11306, 54152, 25732, 65376, 35511, 5342, 10887, 53003, 36384, 45501, 28701, 19736, 42682, 50157, 2125, 66853, 58320, 27342, 24621, 21109, 23342, 26780, 3738, 30468, 46504, 35896, 22269, 26218, 29149, 26072, 52848, 681, 15127, 45795, 28937, 24784, 65105, 41586, 54879, 36165, 26680, 37613, 54177, 63917, 51954, 34921, 39270, 36362, 46987, 66032, 34496, 27270, 54543, 24521, 48121, 6541, 27252, 26236, 58367, 53892, 65141, 54564, 29331, 47108, 27063, 54949, 66657, 28983, 54841, 13352, 21805, 8006, 29262, 12141, 37625, 729, 3416, 36886, 39252, 42497, 14154, 3994, 39415, 7359, 27251, 55669, 47092, 28802, 50902, 34453, 19621, 65935, 35494, 20280, 57180, 11400, 35307, 47146, 54647, 35269, 30390, 26059, 37476, 66456, 37678, 6946, 47035, 36261, 454, 26684, 26158, 54315, 62935, 32106, 45847, 55372, 24168, 30735, 25974, 65439, 39154, 34557, 29234, 29215, 9155, 60419, 65709, 18988, 63717, 52883, 25691, 39379, 36376, 62393, 33016, 24755, 55225, 35359, 37453, 23573, 66685, 55545, 47187, 35327, 54626, 37362, 51961, 33838, 61469, 3753, 26577, 50143, 66890, 37343, 24705, 59262, 29568, 67328, 36256, 3214, 66611, 1978, 34439, 65235, 49207, 65812, 46046, 14499, 3615, 25466, 26404, 24165, 47642, 39445, 53186, 24590, 26837, 35837, 26760, 35750, 25182, 34686, 27344, 27092, 51277, 9645, 39230, 27665, 64224, 37248, 24171, 41325, 26151, 31724, 30704, 44967, 28009, 67269, 47290, 31049, 63931, 56259, 64719, 49937, 49618, 58896, 31868, 3229, 23288, 27362, 59674, 61115, 22910, 24780, 61256, 66627, 59810, 29363, 34776, 35387, 42584, 27401, 20057, 34871, 26344, 62922, 23981, 26803, 37264, 37254, 58682, 28819, 27434, 9163, 30555, 5795, 36177, 55293, 65074, 26202, 64349, 31450, 15110, 55321, 60549, 430, 67406, 27179, 36128, 54719, 20419, 41061, 21317, 26133, 51764, 63137, 65818, 22376, 54226, 52374, 34539, 48653, 66736, 14136, 3473, 11402, 30156, 66966, 29453, 47840, 3732, 39418, 53230, 50237, 65976, 20412, 48712, 29207, 25863, 65719, 28631, 66982, 28292, 10595, 50666, 44490, 46251, 37188, 3735, 59457, 50002, 37319, 30578, 10127, 38991, 25450, 12257, 39511, 29210, 36414, 27554, 47004, 40435, 12913, 66873, 39330, 67069, 29005, 15274, 5382, 63075, 35787, 39626, 36351, 3263, 66730, 37144, 49760, 22130, 27059, 48626, 43807, 26775, 38552, 1566, 27417, 33278, 66142, 24439, 20292, 41102, 22691, 24579, 31464, 24748, 62778, 58052, 26262, 52713, 25608, 26211, 54379, 63504, 35998, 36360, 2982, 5438, 51181, 52695, 5762, 24247, 39494, 47312, 23432, 65802, 26484, 45937, 10089, 66304, 45218, 12353, 34780, 27129, 14487, 6234, 31757, 23879, 32344, 25928, 29042, 35683, 417, 34983, 32555, 54490, 29502, 41487, 48528, 9019, 34061, 34891, 35020, 48935, 21100, 66624, 26192, 35311, 39414, 24337, 30149, 57780, 66325, 10741, 49706, 34999, 32395, 42579, 34951, 34014, 22178, 19609, 39237, 65793, 42971, 9317, 50254, 26538, 27645, 37325, 26981, 66713, 63584, 34965, 61661, 66711, 49266, 52569, 56909, 28296, 29037, 60503, 51911, 24145, 35378, 39401, 55104, 49734, 48862, 65987, 2086, 44926, 64117, 39407, 33423, 52891, 45777, 65304, 13287, 54924, 2522, 26516, 19832, 7545, 16451, 61818, 45132, 28339, 54892, 43176, 37868, 35299, 25984, 24452, 28928, 45776, 47949, 47868, 52298, 20072, 51894, 35822, 49440, 59535, 29221, 26346, 1744, 65423, 35927, 13737, 66305, 26271, 53989, 6945, 29147, 9998, 29065, 32630, 50648, 48607, 24075, 26191, 20248, 896, 686, 28826, 50209, 7327, 31234, 1092, 30095, 63438, 63170, 25680, 46794, 20005, 35734, 61451, 26383, 57496, 39457, 26588, 9590, 25265, 52803, 43384, 66749, 54697, 28951, 22896, 67225, 5576, 50796, 3861, 24674, 54741, 37771, 25578, 37238, 46048, 35679, 23339, 1970, 33524, 53708, 65695, 30047, 29145, 55555, 53105, 9459, 57770, 27479, 29792, 3396, 6280, 39413, 61751, 49270, 3279, 37135, 24863, 31316, 37431, 61650, 54594, 8279, 26215, 61471, 28178, 24638, 19927, 39160, 35015, 3698, 49014, 34219, 6545, 23025, 29771, 66596, 64284, 9817, 59280, 58206, 1718, 46528, 34365, 52989, 35114, 14111, 55537, 65934, 27363, 35544, 64570, 3714, 14165, 33958, 55524, 34134, 13124, 24376, 26101, 25210, 26840, 34508, 25796, 31274, 34321, 33049, 35189, 35538, 49404, 35880, 22239, 33730, 4391, 36319, 19890, 66241, 5148, 3189, 47919, 46481, 59328, 24912, 54988, 20489, 35915, 29338, 3388, 19501, 15364, 44162, 67026, 58852, 54979, 13564, 51896, 1580, 45598, 32392, 27117, 46440, 3433, 43851, 54941, 20237, 55062, 35074, 23738, 25794, 35274, 62817, 33068, 20602, 50454, 67008, 26422, 6049, 29266, 5633, 35762, 39508, 25872, 31744, 35624, 26554, 39403, 12954, 1632, 29258, 66346, 27613, 52322, 26523, 26700, 52035, 5444, 48728, 6128, 35487, 31771, 5048, 24461, 31045, 28895, 42457, 35981, 6006, 26168, 63514, 38009, 53154, 54983, 57809, 66674, 27646, 53151, 54071, 26185, 66769, 27137, 26063, 33600, 3519, 61718, 3584, 31442, 27309, 54669, 45979, 37442, 34104, 18488, 34989, 29406, 41682, 57396, 63219, 62395, 52363, 37478, 24455, 51668, 37369, 6166, 66886, 1490, 28985, 46164, 29308, 2020, 3758, 5785, 26517, 36164, 35082, 57366, 29298, 29353, 34936, 4465, 33450, 46006, 45754, 1967, 57343, 64928, 5568, 37087, 31149, 35598, 35041, 35501, 20969, 7091, 29390, 34391, 55704, 24460, 11527, 25725, 47023, 55695, 9731, 30525, 27080, 1484, 34548, 34436, 49301, 24602, 10925, 51950, 29014, 22497, 231, 50289, 25284, 61110, 25248, 62766, 65903, 39376, 3638, 24867, 66722, 12694, 1572, 66129, 20268, 35164, 31191, 39260, 27089, 26805, 64491, 25424, 29903, 265, 647, 30891, 66382, 14355, 65889, 27287, 14613, 26495, 25065, 3445, 39517, 28195, 38234, 39498, 19997, 64122, 37181, 29490, 45369, 55947, 59029, 22252, 33247, 9462, 55133, 56370, 26510, 29509, 34278, 65936, 13519, 54305, 44048, 4749, 32838, 46119, 36010, 37731, 22194, 6311, 30094, 39050, 56615, 39525, 30150, 50913, 44580, 38956, 33875, 63992, 7635, 56500, 24103, 29117, 37831, 23158, 31173, 32414, 25415, 65366, 45250, 65916, 30424, 65937, 16162, 53265, 4618, 24385, 57334, 2417, 25876, 36419, 66389, 3393, 67285, 37691, 26949, 59190, 35723, 65908, 33056, 22652, 59443, 25913, 24350, 66608, 7752, 59351, 55969, 1666, 63934, 36471, 35664, 64496, 47344, 35090, 34876, 54498, 42179, 39364, 32153, 6871, 29173, 34655, 50244, 28870, 39399, 13839, 24710, 14514, 59690, 47431, 14300, 32777, 41879, 30249, 26530, 25250, 59137, 58825, 39232, 24457, 6974, 35407, 51457, 42796, 5201, 11484, 57614, 53032, 36314, 35027, 48379, 60168, 26458, 29448, 52753, 50175, 29096, 54717, 61069, 21667, 58073, 20988, 664, 55397, 35257, 12052, 24257, 33023, 26786, 27327, 35581, 25999, 5751, 38054, 67031, 29170, 37539, 6986, 50709, 52379, 33657, 16159, 31582, 56730, 27259, 24126, 47062, 48227, 25492, 27534, 54882, 24593, 36283, 46741, 54618, 37287, 35914, 59218, 2069, 37281, 50646, 28827, 29392, 66183, 20367, 29106, 60330, 18967, 49340, 25768, 31648, 22085, 32339, 63371, 45300, 34981, 66546, 50008, 45822, 21456, 16100, 24712, 2593, 12432, 29064, 29322, 3508, 2532, 55743, 35541, 39487, 63622, 33465, 9924, 20499, 56611, 55769, 36225, 29618, 24176, 54051, 17712, 11359, 19837, 22636, 2065, 40913, 6418, 1846, 22818, 35951, 45574, 9025, 29736, 1793, 57220, 26053, 26198, 34402, 51741, 25723, 35106, 23638, 44963, 52618, 36140, 27615, 37277, 36204, 39442, 3467, 54126, 49843, 66200, 52687, 54862, 57564, 36473, 44212, 52878, 4653, 26001, 35280, 60975, 38195, 63995, 27438, 39167, 21525, 36149, 46906, 27902, 63709, 43159, 10460, 44773, 28485, 3334, 14619, 28236, 61768, 14313, 21197, 34015, 26594, 50776, 17714, 53992, 53978, 13202, 61395, 38994, 27600, 24391, 66583, 44875, 55681, 63672, 67314, 29731, 51312, 34797, 34778, 23367, 29051, 26433, 39431, 39067, 4243, 66327, 47030, 46375, 3493, 24407, 20665, 2089, 53023, 67400, 64913, 51094, 39703, 28945, 56252, 67292, 19808, 36340, 49091, 604, 24880, 55699, 35695, 27218, 39247, 25376, 20332, 11910, 55760, 63522, 47568, 34843, 18593, 35410, 22613, 46981, 24738, 28098, 51945, 52936, 59390, 37932, 7920, 42587, 25285, 66911, 34, 55344, 44051, 756, 34598, 22882, 24856, 9769, 44509, 53454, 29031, 22848, 19413, 54583, 20807, 57869, 35759, 60861, 66369, 6059, 54402, 43536, 27480, 26351, 59021, 38604, 39295, 11980, 3697, 4421, 21046, 39283, 21361, 67271, 24166, 52408, 35893, 33421, 25867, 35638, 26126, 20768, 66333, 66999, 35415, 28883, 66282, 28266, 49408, 26533, 49739, 65999, 1731, 26214, 44861, 9350, 28579, 59521, 24548, 49269, 36447, 26628, 50195, 51419, 3248, 43976, 7264, 34953, 36276, 45846, 12111, 5920, 37717, 20813, 49066, 26304, 341, 39528, 34739, 12252, 23166, 11048, 13141, 54405, 22362, 29500, 66407, 29141, 25029, 59247, 42960, 35795, 25983, 24157, 45962, 55362, 57373, 8264, 46791, 20718, 1483, 53397, 62356, 39523, 22125, 53122, 14644, 46441, 20276, 28125, 13525, 10791, 7328, 23825, 37843, 5370, 34419, 49342, 11983, 43537, 23609, 64075, 36239, 29335, 32482, 39186, 50401, 60580, 26311, 23754, 37557, 32507, 57997, 64561, 19759, 37698, 66335, 29514, 8075, 13905, 26097, 37560, 31088, 1670, 44534, 13797, 33761, 23008, 65810, 5784, 45023, 34358, 19578, 11262, 47835, 28886, 49121, 39371, 26574, 33473, 38876, 66616, 57839, 42852, 35968, 22397, 26904, 745, 58308, 42686, 34181, 34751, 34827, 43432, 57250, 35376, 36311, 44560, 67227, 38589, 20109, 26182, 37507, 59683, 64670, 28347, 65352, 34399, 37562, 57161, 25588, 58719, 32614, 35600, 926, 35484, 26305, 46793, 9738, 19597, 32226, 59161

In [34]:
boo['readmit_' + '30d'] = df_results.loc[rows, 'readmit_' + '30d']

flag = 'd30'

cols_flag = [col for col in results['pred_values'] if flag in col]

boo[cols_flag] = results['pred_values'][cols_flag]

boo

,stay_id,cost_per_day_stay,total_readmission_cost,avg_cost_of_prev_stays,readmit_30d,logreg_d30,rf_d30,lightgbm_d30
X,,,,,,,,
13687,1c7e06b6-7da5-69dd-ff2f-df2394107272,5053.02,NaN,NaN,0,0.373445,0.017321,0.002220
16868,234e933e-6812-955f-7c59-ea8b527160aa,1968.47,NaN,NaN,0,0.393514,0.194508,0.014668
6924,05c7ca14-fdb6-df9d-9515-0eb2ad98509d,525.56,NaN,NaN,0,0.269175,0.020874,0.002915
7041,c9edf56d-70ac-b973-1c0f-5bce0dfbe661,406.83,NaN,NaN,0,0.458464,0.000000,0.001108
10643,f068eb0b-d00a-ca9e-53a0-07e18171cba9,3961.01,NaN,NaN,0,0.116136,0.301576,0.105888
...,...,...,...,...,...,...,...,...
57253,07e79f16-3604-4f22-e9c0-b218da02154c,376.56,NaN,NaN,0,0.077234,0.000000,0.000157
59697,8386eee1-77e1-c946-85ce-2d19979295a7,3880.25,NaN,NaN,0,0.060526,0.011354,0.000567
61959,0a72f89e-cf52-659e-0d12-f2e64d29c616,964.09,NaN,NaN,0,0.063207,0.000000,0.001051
11130,a1195b5f-423c-9f65-a60e-6f1bcecd8ea6,6602.84,NaN,166.97,0,0.637811,0.054013,0.004071
82931,65cc0188-9fa1-4323-ad7a-599761bd56c9,692.52,166.97,166.97,0,0.176881,0.334840,0.040348

In [35]:
df_cost = boo.copy()

In [48]:
a = 1
b = None
min(a,b)

TypeError: '<' not supported between instances of 'NoneType' and 'int'

In [47]:
results['pred_values']

,readmit_30d,readmit_90d,logreg_d30,logreg_d90,rf_d30,rf_d90,lightgbm_d30,lightgbm_d90
X,,,,,,,,
13687,0,0,0.373445,0.404117,0.017321,0.018723,0.002220,0.011458
16868,0,0,0.393514,0.416884,0.194508,0.189227,0.014668,0.089942
6924,0,0,0.269175,0.487070,0.020874,0.164600,0.002915,0.030209
7041,0,0,0.458464,0.429166,0.000000,0.018963,0.001108,0.005323
10643,0,0,0.116136,0.146796,0.301576,0.206495,0.105888,0.028919
...,...,...,...,...,...,...,...,...
57253,0,0,0.077234,0.147388,0.000000,0.038779,0.000157,0.002395
59697,0,0,0.060526,0.141953,0.011354,0.000000,0.000567,0.004051
61959,0,0,0.063207,0.179909,0.000000,0.006070,0.001051,0.003287
11130,0,0,0.637811,0.717717,0.054013,0.076367,0.004071,0.013965
82931,0,0,0.176881,0.388061,0.334840,0.507685,0.040348,0.128152

In [37]:
#for row in results['thresholds'].index:
 #   print(row) 


results['thresholds']

,readmit_30d,readmit_90d,logreg_d30_0.05,logreg_d30_0.1,logreg_d30_0.15,logreg_d30_0.2,logreg_d30_0.25,logreg_d30_0.3,logreg_d30_0.35,logreg_d30_0.4,...,lightgbm_d90_0.5,lightgbm_d90_0.55,lightgbm_d90_0.6,lightgbm_d90_0.65,lightgbm_d90_0.7,lightgbm_d90_0.75,lightgbm_d90_0.8,lightgbm_d90_0.85,lightgbm_d90_0.9,lightgbm_d90_0.95
X,,,,,,,,,,,,,,,,,,,,,
13687,0,0,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
16868,0,0,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
6924,0,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7041,0,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
10643,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57253,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59697,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
61959,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11130,0,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
82931,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [46]:
gains

,logreg_d30_0.05,logreg_d30_0.1,logreg_d30_0.15,logreg_d30_0.2,logreg_d30_0.25,logreg_d30_0.3,logreg_d30_0.35,logreg_d30_0.4,logreg_d30_0.45,logreg_d30_0.5,...,lightgbm_d30_0.5,lightgbm_d30_0.55,lightgbm_d30_0.6,lightgbm_d30_0.65,lightgbm_d30_0.7,lightgbm_d30_0.75,lightgbm_d30_0.8,lightgbm_d30_0.85,lightgbm_d30_0.9,lightgbm_d30_0.95
X,,,,,,,,,,,,,,,,,,,,,
13687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10643,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2117742306640,-495.003234,-161.063234,-161.063234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
total_avoided,-495.003234,-161.063234,-161.063234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0